#!/usr/bin/env python

import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522

from gpiozero import Motor
from gpiozero import Servo
from time import sleep

servo = Servo(25)
motor1 = Motor(4, 14)

reader = SimpleMFRC522()

try:
        id, text = reader.read()
        print(id)
        print(text)
        
        if(text == "UntitledPaintingA"){
                motor1 = motor1.forward(0.5)
        }
          
finally:
        GPIO.cleanup()
