#!/usr/bin/env python

import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522
from time import sleep

motor1pin = 17
motor2pin = 27

GPIO.setmode(GPIO.BCM)
GPIO.setup(motor1pin, GPIO.OUT)
GPIO.setup(motor2pin, GPIO.OUT)

pwm1 = GPIO.PWM(motor1pin, 50) # GPIO 17 for PWM with 50Hz
pwm2 = GPIO.PWM(motor2pin, 50) # GPIO 27 for PWM with 50Hz

pwm1.start(0)
pwm2.start(0)

paintingA = '222767519619'
paintingB = '419146909097'

reader = SimpleMFRC522()

def SetAngle(angle, servoPIN, pwm):
	duty = angle / 18 + 2
	GPIO.output(servoPIN, True)
	pwm.ChangeDutyCycle(duty)
	sleep(1)
	GPIO.output(servoPIN, False)
	pwm.ChangeDutyCycle(0)

try:
    id, text = reader.read()
    rfidTag = str(id)
    
    print(id)
    print(text)

    if rfidTag == paintingA:
        print("yes, A")
        
        SetAngle(90, motor1pin, pwm1)
        sleep(30)
        SetAngle(0, motor1pin, pwm1)
        

    elif rfidTag == paintingB:
        print("yes, B")
    
        SetAngle(90, motor2pin, pwm2)
        sleep(30)
        SetAngle(0, motor2pin, pwm2)   
            
    else:
        print("no")
        GPIO.cleanup()

except KeyboardInterrupt:
  pwm1.stop()
  pwm2.stop()
  GPIO.cleanup()
