#!/usr/bin/env python

import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522
import time

servoPIN = 17
GPIO.setmode(GPIO.BCM)
GPIO.setup(servoPIN, GPIO.OUT)

p = GPIO.PWM(servoPIN, 50) # GPIO 17 for PWM with 50Hz
p.start(2.5) # Initialization

paintingA = 'UntitledPaintingA'
reader = SimpleMFRC522()

try:
    id, text = reader.read()
    text2 = str(text)
    
    print(id)
    print(text)

    if text2 == paintingA:
        print("yes")
    else:
        print("no")
        GPIO.cleanup()

except KeyboardInterrupt:
  p.stop()
  GPIO.cleanup()
