#!/usr/bin/env python

import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522
from time import sleep

servoPIN = 17
GPIO.setmode(GPIO.BCM)
GPIO.setup(servoPIN, GPIO.OUT)

pwm = GPIO.PWM(servoPIN, 50) # GPIO 17 for PWM with 50Hz

pwm.start(0)

paintingA = '632265873354'
reader = SimpleMFRC522()

def SetAngle(angle):
	duty = angle / 18 + 2
	GPIO.output(servoPIN, True)
	pwm.ChangeDutyCycle(duty)
	sleep(1)
	GPIO.output(servoPIN, False)
	pwm.ChangeDutyCycle(0)

try:
    id, text = reader.read()
    text2 = str(id)
    
    print(id)
    print(text)

    if text2 == paintingA:
        print("yes")
        
        SetAngle(90)
        SetAngle(45)
        SetAngle(170)
        SetAngle(0)
    else:
        print("no")
        GPIO.cleanup()

except KeyboardInterrupt:
  pwm.stop()
  GPIO.cleanup()
